{{- if or (eq .Values.global.edition "pro") (eq .Values.global.edition "enterprise") }}
{{- if eq .Values.global.deploymentMode "oss" }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-setup
  labels:
    {{- include "airbyte.labels" . | nindent 4 }}
    {{- if .Values.keycloakSetup.extraLabels }}
    {{ toYaml (mergeOverwrite .Values.keycloakSetup.extraLabels .Values.global.extraLabels) | nindent 4 }}
    {{- end }}
    {{- if .Values.keycloakSetup.podLabels}}
    {{- include "common.tplvalues.render" (dict "value" .Values.keycloakSetup.podLabels "context" $) | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": "post-install, post-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  completions: 1
  template:
    spec:
      serviceAccountName: {{ .Values.global.serviceAccountName }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
          {{- printf "- name: %s" .name | nindent 8 }}
          {{- end }}
      {{- end }}
      restartPolicy: Never
      {{- if .Values.keycloakSetup.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.keycloakSetup.nodeSelector "context" $) | nindent 6 }}
      {{- end }}
      {{- if .Values.keycloakSetup.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.keycloakSetup.tolerations "context" $) | nindent 6 }}
      {{- end }}
      {{- if .Values.keycloakSetup.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.keycloakSetup.affinity "context" $) | nindent 6 }}
      {{- end }}
      initContainers:
        - name: keycloak-readiness-check
          image: {{ include "imageUrl" (list .Values.keycloakSetup.initContainers.keycloakReadinessCheck.image $) }}
          command: [ "sh", "-c", "until curl --output /dev/null --head --fail http://${KEYCLOAK_INTERNAL_HOST}/auth/health/ready; do sleep 1; done;" ]
          env:
            - name: KEYCLOAK_INTERNAL_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.configMapName | default (printf "%s-airbyte-env" .Release.Name) }}
                  key: KEYCLOAK_INTERNAL_HOST
          securityContext: 
            {{- toYaml .Values.keycloakSetup.initContainerSecurityContext | nindent 12 }}
        {{- if .Values.keycloakSetup.extraInitContainers }}
        {{- toYaml .Values.keycloakSetup.extraInitContainers | nindent 8 }}
        {{- end }}
      containers:
        - name: airbyte-keycloak-setup-container
          image: {{ include "imageUrl" (list .Values.keycloakSetup.image $) }}
          imagePullPolicy: "{{ .Values.keycloakSetup.image.pullPolic }}"
          env:
            - name: AIRBYTE_URL 
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.configMapName | default (printf "%s-airbyte-env" .Release.Name) }}
                  key: AIRBYTE_URL 
            - name: KEYCLOAK_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secretName | default (printf "%s-airbyte-secrets" .Release.Name) }}
                  key: KEYCLOAK_ADMIN_USER
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secretName | default (printf "%s-airbyte-secrets" .Release.Name) }}
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: KEYCLOAK_INTERNAL_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.configMapName | default (printf "%s-airbyte-env" .Release.Name) }}
                  key: KEYCLOAK_INTERNAL_HOST

            {{- include "airbyte.database.envs" . | nindent 12 }}
            {{- include "airbyte.enterprise.instanceAdmin" . | nindent 12 }} 
            {{- include "airbyte.enterprise.identityProvider" . | nindent 12 }} 
            {{- include "airbyte.keycloak.database.envs" . | nindent 12 }}

            # Values from secret
            {{- if .Values.keycloakSetup.secrets }}
            {{- range $k, $v := .Values.keycloakSetup.secrets }}
            - name: {{ $k }}
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: {{ $k }}
            {{- end }}
            {{- end }}

            # Values from env
            {{- if .Values.keycloakSetup.env_vars }}
            {{- range $k, $v := mergeOverwrite .Values.keycloakSetup.env_vars .Values.global.env_vars }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
            {{- end }}

            # Values from extraEnv for more compability(if you want to use external secret source or other stuff)
            {{- if .Values.keycloakSetup.extraEnv }}
            {{- toYaml .Values.keycloakSetup.extraEnv | nindent 12 }}
            {{- end }}

          {{- if .Values.keycloakSetup.resources }}
          resources: {{- toYaml .Values.keycloakSetup.resources | nindent 10 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.global.airbyteYml }}
            - name: airbyte-yml-volume
              mountPath: /app/configs/airbyte.yml
              subPath: fileContents
              readOnly: true
            {{- end }}
          {{- if .Values.keycloakSetup.extraVolumeMount }}
          {{- toYaml .Values.keycloakSetup.extraVolumeMounts | nindent 10 }}
          {{- end }}
          {{- if .Values.keycloakSetup.containerSecurityContext }}
          securityContext: {{- toYaml .Values.keycloakSetup.containerSecurityContext | nindent 10 }}
          {{- end }}
        {{- if .Values.keycloakSetup.extraContainers }}
        {{ toYaml .Values.keycloakSetup.extraContainers | nindent 8 }}
        {{- end }}
        {{- if .Values.global.extraContainers }}
        {{ toYaml .Values.global.extraContainers | nindent 8 }}
        {{- end }}
      securityContext: {{- toYaml .Values.keycloakSetup.podSecurityContext | nindent 6 }}
      volumes:
        {{- if .Values.global.airbyteYml }}
        - name: airbyte-yml-volume
          secret:
            secretName: {{ .Release.Name }}-airbyte-yml
        {{- end }}
        {{- if .Values.keycloakSetup.extraVolumes }}
        {{- toYaml .Values.keycloakSetup.extraVolumes | nindent 8 }}
        {{- end }}
{{- end }}
{{- end }}
