apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cron
  labels:
    {{- include "airbyte.labels" . | nindent 4 }}
    {{- if .Values.cron.extraLabels }}
    {{ toYaml (mergeOverwrite .Values.cron.extraLabels .Values.global.extraLabels) | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.cron.replicaCount }}
  selector:
    matchLabels:
      {{- include "airbyte.selectorLabels" . | nindent 6 }}
      {{- if .Values.cron.extraSelectorLabels }}
      {{ toYaml (mergeOverwrite .Values.cron.extraSelectorLabels .Values.global.extraSelectorLabels) | nindent 6 }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- include "airbyte.selectorLabels" . | nindent 8 }}
        {{- if .Values.cron.extraSelectorLabels }}
        {{ toYaml (mergeOverwrite .Values.cron.extraSelectorLabels .Values.global.extraSelectorLabels) | nindent 8 }}
        {{- end }}
        {{- if .Values.cron.podLabels }}
          {{- include "common.tplvalues.render" (dict "value" .Values.cron.podLabels "context" $) | nindent 8 }}
        {{- end }}
      {{- if .Values.cron.podAnnotations }}
      annotations:
        {{- include "common.tplvalues.render" (dict "value" .Values.cron.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.global.serviceAccountName }}
      automountServiceAccountToken: true
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
          {{- printf "- name: %s" .name | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if .Values.cron.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.cron.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.cron.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.cron.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.cron.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.cron.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.cron.extraInitContainers }}
      initContainers:
      {{- toYaml .Values.cron.extraInitContainers | nindent 6 }}
      {{- end }}
      containers:
        - name: airbyte-cron
          image: {{ include "imageUrl" (list .Values.cron.image $) }}
          imagePullPolicy: "{{ .Values.cron.image.pullPolicy }}"
          env:
          {{- if eq .Values.global.deploymentMode "oss"  }}
          - name: AIRBYTE_VERSION
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-airbyte-env
                key: AIRBYTE_VERSION
          - name: CONFIGS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-airbyte-env
                key: CONFIGS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION
          - name: MICROMETER_METRICS_ENABLED
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-airbyte-env
                key: MICROMETER_METRICS_ENABLED
          - name: MICROMETER_METRICS_STATSD_FLAVOR
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-airbyte-env
                key: MICROMETER_METRICS_STATSD_FLAVOR
          - name: MICRONAUT_ENVIRONMENTS
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-airbyte-env
                key: CRON_MICRONAUT_ENVIRONMENTS
          - name: TEMPORAL_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-airbyte-env
                key: TEMPORAL_HOST
          - name: SEGMENT_WRITE_KEY
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-airbyte-env
                key: SEGMENT_WRITE_KEY
          - name: STATSD_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-airbyte-env
                key: STATSD_HOST
          - name: STATSD_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-airbyte-env
                key: STATSD_PORT
          - name: TRACKING_STRATEGY
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-airbyte-env
                key: TRACKING_STRATEGY
          - name: WORKFLOW_FAILURE_RESTART_DELAY_SECONDS
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-airbyte-env
                key: WORKFLOW_FAILURE_RESTART_DELAY_SECONDS
          - name: WORKLOAD_API_BEARER_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ index .Values.cron "workloadApi" "bearerTokenSecretName" | default (printf "%s-airbyte-secrets" .Release.Name ) }}
                key: {{ index .Values.cron "workloadApi" "bearerTokenSecretKey" | default "WORKLOAD_API_BEARER_TOKEN" }}
          - name: WORKLOAD_API_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-airbyte-env
                key: WORKLOAD_API_HOST
          - name: WORKSPACE_DOCKER_MOUNT
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-airbyte-env
                key: WORKSPACE_DOCKER_MOUNT
          - name: WORKSPACE_ROOT
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-airbyte-env
                key: WORKSPACE_ROOT

          # Database
          {{- include "airbyte.database.envs" . | nindent 10 }}

          {{- end }}


          # Values from secret
          {{- if .Values.cron.secrets }}
          {{- range $k, $v := .Values.cron.secrets }}
          - name: {{ $k }}
            valueFrom:
              secretKeyRef:
                name: cron-secrets
                key: {{ $k }}
          {{- end }}
          {{- end }}

          # Values from env
          {{- if or .Values.cron.env_vars .Values.global.env_vars }}
          {{- range $k, $v := mergeOverwrite .Values.cron.env_vars .Values.global.env_vars }}
          - name: {{ $k }}
            value: {{ $v | quote }}
          {{- end }}
          {{- end }}

          # Values from extraEnv for more compability(if you want to use external secret source or other stuff)
          {{- if .Values.cron.extraEnv }}
          {{- toYaml .Values.cron.extraEnv | nindent 10 }}
          {{- end }}

          {{- if .Values.cron.containerSecurityContext }}
          securityContext: {{- toYaml .Values.cron.containerSecurityContext | nindent 12 }}
          {{- end }}

          {{- if .Values.cron.resources }}
          resources: {{- toYaml .Values.cron.resources | nindent 12 }}
          {{- end }}

          {{- if .Values.cron.extraVolumeMounts }}
          volumeMounts: {{ toYaml .Values.cron.extraVolumeMounts | nindent 10 }}
          {{- end }}

        {{- if .Values.cron.extraContainers }}
          {{ toYaml .Values.cron.extraContainers | nindent 8 }}
        {{- end }}
        {{- if .Values.global.extraContainers }}
          {{ toYaml .Values.global.extraContainers | nindent 8 }}
        {{- end }}
      securityContext: {{- toYaml .Values.cron.podSecurityContext | nindent 10 }}
      {{- if .Values.cron.extraVolumes }}
      volumes: {{ toYaml .Values.cron.extraVolumes | nindent 6 }}
      {{- end }}
