{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: airbyte-db-svc
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-1"
  labels:
    {{ include "airbyte.databaseLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      protocol: TCP
  selector:
    {{ include "airbyte.databaseSelectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: airbyte-db
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-1"
  labels:
    {{ include "airbyte.databaseLabels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: airbyte-db-svc
  selector:
    matchLabels:
      {{ include "airbyte.databaseSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "airbyte.databaseSelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: airbyte-db-container
          image: "{{ .Values.postgresql.image.repository }}:{{ ((.Values.global.image).tag) | default .Chart.AppVersion }}"
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.postgresqlDatabase }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.postgresqlPassword }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.postgresqlUsername }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            {{- if include "postgresql.tlsEnabled" . }}
            - name: PGSSLCERT
              value: /etc/ssl/certs/cert.crt
            - name: PGSSLKEY
              value: /etc/ssl/private/cert.key
            - name: PGSSLROOTCERT
              value: /etc/ssl/certs/ca.crt
            {{- end }}
          ports:
            - containerPort: 5432
          securityContext: {{- toYaml .Values.postgresql.containerSecurityContext | nindent 12 }}
          volumeMounts:
            - name: airbyte-volume-db
              mountPath: /var/lib/postgresql/data
            {{- if include "postgresql.tlsEnabled" . }}
            - name: certs
              mountPath: /etc/ssl/certs
              subPath: cert.crt
            - name: certs
              mountPath: /etc/ssl/private
              subPath: cert.key
            - name: certs
              mountPath: /etc/ssl/certs
              subPath: ca.crt
            {{- end }}
      {{- with .Values.postgresql.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.postgresql.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.postgresql.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext: {{- toYaml .Values.postgresql.podSecurityContext | nindent 8 }}

      {{- if include "postgresql.tlsEnabled" . }}
      volumes:
        - name: tls-secret
          secret:
            secretName: certificates-tls-secret
      {{- end }}

  volumeClaimTemplates:
  - metadata:
      name: airbyte-volume-db
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Mi
{{- end }}
