{{- if eq .Values.global.deploymentMode "oss"  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-airbyte-secrets
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
  labels:
    {{- include "airbyte.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ if eq .Values.global.logs.accessKey.existingSecret "" -}}
  AWS_ACCESS_KEY_ID: {{ .Values.global.logs.accessKey.password | quote }}
  {{- end }}
  {{ if eq .Values.global.logs.secretKey.existingSecret "" -}}
  AWS_SECRET_ACCESS_KEY: {{ .Values.global.logs.secretKey.password | quote }}
  {{- end }}
  {{ if eq .Values.externalDatabase.existingSecret "" -}}
  DATABASE_PASSWORD: {{ .Values.externalDatabase.password | default .Values.postgresql.postgresqlPassword | quote }}
  {{ end -}}
  DATABASE_USER: {{ include "airbyte.database.user" . }}
  STATE_STORAGE_MINIO_ACCESS_KEY: {{ .Values.minio.auth.rootUser | quote }}
  STATE_STORAGE_MINIO_SECRET_ACCESS_KEY: {{ .Values.minio.auth.rootPassword | quote }}
{{- end }}

