name: Test helm charts(on push)

on:
  push:
    paths:
      - "charts/**"
      - "!charts/**/Chart.yaml"
      - "!charts/**/Chart.lock"
      - "!charts/**/README.md"
  workflow_dispatch:

jobs:
  test-helm-charts:
    name: Test helm charts
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Helm lint all charts
        shell: bash
        run: |
          declare -a StringArray=("airbyte-bootloader" "airbyte-server" "airbyte-temporal" "airbyte-webapp" "airbyte-pod-sweeper" "airbyte-worker" "airbyte-metrics" "airbyte-cron" "airbyte-connector-builder-server")
          for val in ${StringArray[@]}; do
            pushd ./charts/${val} && helm dep update && popd
          done
          pushd charts/airbyte
          mv Chart.yaml Chart.yaml.old
          mv Chart.yaml.test Chart.yaml
          mv values.yaml values.yaml.old
          mv values.yaml.test values.yaml
          helm dep update
          helm lint --with-subcharts
          popd
      
      - name: Validate
        uses: nlamirault/helm-kubeconform-action@v0.1.0
        with:
          charts: ./charts/airbyte

      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Try the cluster !
        run: kubectl get pods -A
      
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      
      - name: Deploy helm chart to k3s cluster
        shell: bash
        run: |
          pushd charts/airbyte
          helm dep update 
          helm upgrade --install --wait --timeout=10m --debug airbyte ./
      
      - name: Perform curl requests to test out the deployment
        shell: bash
        run: |
          minikube service list
          minikube service airbyte-airbyte-server-svc --url
          if [[ "$(curl -s -o /dev/null -w ''%{http_code}'' $()/api/v1/health)" != "200" ]];
          then
            exit 25
          fi
