name: Test helm charts(on push)

on:
  push:
    paths:
      - "charts/**"
      - "!charts/**/Chart.yaml"
      - "!charts/**/Chart.lock"
      - "!charts/**/README.md"
  workflow_dispatch:

jobs:
  test-helm-charts:
    name: Test helm charts before publishing
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install kubeconform
        shell: bash
        run: go install github.com/yannh/kubeconform/cmd/kubeconform@latest

      - name: Helm lint all charts
        shell: bash
        run: |
          pushd charts/airbyte
          mv Chart.yaml Chart.yaml.old
          mv Chart.yaml.test Chart.yaml
          mv values.yaml values.yaml.old
          mv values.yaml.test values.yaml
          helm dep update
          helm lint --with-subcharts
          popd
      
      - name: Helm template and kubeconform template
        shell: bash
        run: |
          pushd charts/airbyte
          helm template airbyte ./ | kubeconform -strict -summary -verbose -exit-on-error
          popd

      - name: Start a local k8s cluster
        uses: jupyterhub/action-k3s-helm@v3
        with:
          k3s-version: v1.21.2+k3s1
          helm-version: v3.9.4
          extra-setup-args: --docker --kube-apiserver-arg service-node-port-range=6000-32767 --kubelet-arg=cgroup-driver=systemd

      - name: Try the cluster !
        uses: Wandalen/wretry.action@master
        with:
          command: kubectl get pods -A
          attempt_limit: 3
          attempt_delay: 3000 # in ms
      
      - name: Deploy helm chart to k3s cluster
        shell: bash
        run: |
          pushd charts/airbyte
          helm dep update 
          helm upgrade --install --wait --timeout=10m --debug airbyte ./
      
      - name: Perform curl requests to test out the deployment
        shell: bash
        run: |
          kubectl expose $(kubectl get po -l app.kubernetes.io/name=server -o name) --name exposed-server-svc --type NodePort --overrides '{ "apiVersion": "v1","spec":{"ports": [{"port":8001,"protocol":"TCP","targetPort":8001,"nodePort":8001}]}}'
          if [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8000/api/v1/health)" != "200" ]];
          then
            exit 25
          fi
