name: Test helm charts(on push)

on:
  push:
    paths:
      - "charts/**"
      - "!charts/**/Chart.yaml"
      - "!charts/**/Chart.lock"
      - "!charts/**/README.md"
  workflow_dispatch:

jobs:
  test-helm-charts:
    name: Test helm charts
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Helm lint all charts
        shell: bash
        run: |
          declare -a StringArray=("airbyte-bootloader" "airbyte-server" "airbyte-temporal" "airbyte-webapp" "airbyte-pod-sweeper" "airbyte-worker" "airbyte-metrics" "airbyte-cron" "airbyte-connector-builder-server")
          for val in ${StringArray[@]}; do
            pushd ./charts/${val} && helm dep update && popd
          done
          pushd charts/airbyte
          helm dep update
          helm lint --with-subcharts
          popd
      
      - name: Validate
        uses: nlamirault/helm-kubeconform-action@v0.1.0
        with:
          charts: ./charts/airbyte

      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Try the cluster !
        run: kubectl get pods -A
      
      - name: Install tmate and it's dependencies
        uses: Wandalen/wretry.action@master
        with:
          command: |
            sudo apt-get -y install tmate
          attempt_limit: 3
          attempt_delay: 2000 # in ms

      - name: Start tmate session in background
        shell: bash
        run: |
          tmate -S /tmp/tmate.sock new-session -d               # Launch tmate in a headless mode
          tmate -S /tmp/tmate.sock wait tmate-ready             # Blocks until the SSH connection is established
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'    # Prints the SSH connection string
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh_ro}' # Prints the read-only SSH connection string
          tmate -S /tmp/tmate.sock display -p '#{tmate_web}'    # Prints the web connection string
          tmate -S /tmp/tmate.sock display -p '#{tmate_web_ro}' # Prints the read-only web connection string
      
      - name: Deploy helm chart to k3s cluster
        shell: bash
        run: |
          pushd charts/airbyte
          helm dep update 
          helm upgrade --install --wait --timeout=10m --debug airbyte ./
      
      - name: Perform curl requests to test out the deployment
        shell: bash
        run: |
          echo "Sleeping for 300 seconds to wait for server to fully start"
          sleep 300
          kubectl port-forward svc/airbyte-airbyte-server-svc 8001:8001 &
          curl localhost:8001/api/v1/health
          curl -I localhost:8001/api/v1/health
          if [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8001/api/v1/health)" != "200" ]];
          then
            exit 25
          fi
      
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
